name: Setup Go
description: Set up Go toolchain and configure access to private modules

inputs:
  go-version:
    description: Go version to install
    required: false
    default: "1.25.5"
  token:
    description: Token for private modules
    required: true

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        token: ${{ inputs.token }}
