name: Setup Go
description: Set up the Go toolchain and configure private module access

inputs:
  go-version:
    description: Go version to install
    required: false
    default: "1.25.5"

runs:
  using: composite
  steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Configure access to private Go modules
      shell: bash
      run: |
        echo "GOPRIVATE=github.com/ezex-io/*" >> "$GITHUB_ENV"
